### ISSUE TITLE
Running on Home Assistant OS

### ISSUE THREAD

**Issue by backslashV** [jrconlin/sunpower_hass#7]
Hello,
I have the Home Assistant OS installed on a rPi. The terminal doesn't recognized commands like python, virtualenv, pip, etc. How can I use this script still?

**Comment by jrconlin** [comment]
Sadly, I don't have an answer. 

For what it's worth, I've kinda/sorta given up on trying to hack around Sunpower's terrible website. Recently I got an email saying that I now need to download and install an app in order to access their website, and yeah, no, hard pass. Installing their app is not going to happen. 

Instead, I run a separate Pi 3 that I've got plugged into my monitoring box. It's running a super simple python CGI script that queries the installer port (see the [direct](https://github.com/jrconlin/sunpower_hass/tree/main/direct) page that shows what I've done. That interface is absolutely queryable by HASS (and, again, I show what you need to add.)

Honestly, I should just drop the original sniffer app.

**Comment by backslashV** [comment]
Thank you for your response. Yes, them not providing an API is pure nonsense. I have created a web scraper myself which is running on a rPi zero, a separate device from the one running Home Assistant. I was just looking for a solution to run it locally on the HA device.

**Comment by jrconlin** [comment]
Oh! In that case, absolutely look at tapping into the installer port in the controller box. You'll need something that can support a network connection, so I don't think the zero will work there. IIRC, pi3b's go for about $35 currently. You really won't believe the amount of info you can get. (I can poll individual panel temperatures and wattage at 5 minute intervals) 

Way more useful than the site.
